### ISSUE TITLE
LineageOS-14.1 bootloop fix?

### ISSUE THREAD

**Issue by r15ch13** [TeamWin/android_device_zuk_Z1#5]
https://www.reddit.com/r/LineageOS/comments/5riech/how_fix_twrp_recovery_boot_loop_after_lineageos/

Running `dd if=/dev/zero of=/dev/block/bootdevice/by-name/misc count=1 bs=32` worked for LineageOS-14.1

Can the bootloop be fixed by adding `misc` to the `recovery.fstab`?
```
/misc         emmc       /dev/block/bootdevice/by-name/misc
```

**Comment by brancomat** [comment]
In this thread there's a twrp-3.1.0-0-ham build that should fix the bootloop (I'm not sure why it's not on the official twrp site):
https://forum.xda-developers.com/zuk-z1/help/starting-twrp-recovery-official-lineage-t3577201

edit: tried it, everething went fine, now LineageOS OTA updates are also working.

**Comment by r15ch13** [comment]
As a quick fix I use an update-script that I run after updating LineageOS.
```
assert(getprop("ro.product.device") == "Z1" || getprop("ro.build.product") == "Z1" || abort("E3004: This package is for device: Z1; this device is " + getprop("ro.product.device") + "."););
ui_print("> Fixing Bootloop!");
run_program("/sbin/busybox", "dd", "if=/dev/zero", "of=/dev/block/platform/msm_sdcc.1/by-name/misc", "count=1", "bs=32");
```

[ham-bootloop-fix.zip](https://github.com/TeamWin/android_device_zuk_Z1/files/1466344/ham-bootloop-fix.zip) (MD5: `d53a4885f61b5b9ee90bd696e90f449b`)

**Comment by n0p** [comment]
I am using the last TWRP, LineageOS and Gapps available, and I had to execute the comand described by @r15ch13 to be able to boot lineageOS, It was entering into recovery every time

**Comment by brancomat** [comment]
@n0p: By last TWRP available do you mean the last _officialy_ distributed for the Z1 (3.0.2) or the last version available (3.1.1)?

**Comment by n0p** [comment]
The last officially distributed

**Comment by brancomat** [comment]
for the record, it's been fixed in a2b68b9

**Comment by r15ch13** [comment]
@brancomat @bigbiff Thanks! 👍

**Comment by mcmuchenje** [comment]
hi i am using a galaxy a7 and i am trying to install lineage 14.1 i have used the dd if=/dev/zero of=/dev/block/bootdevice/by-name/misc count=1 bs=32 command and also changed the mount path in recovery.fstab however i am still stuck in bootloop twrp 3.2.3-0 please help

**Comment by r15ch13** [comment]
@mcmuchenje This is the wrong project and phone. The fix above will only work for the ZUK Z1.

Did you follow these [instructions](https://wiki.lineageos.org/devices/a7y17lte/install)?

If it still is not working then maybe create a ticket on:
https://github.com/TeamWin/android_device_samsung_a7y17lte
